name: Get all the repos
description: Fetch all repos matching the input
runs:
  using: node16
  main: dist/index.js
inputs:
  token:
    description: 'GitHub API token'
    required: true
  repos:
    description: 'Which repository to deploy'
    required: true
outputs:
  matrix:
    description: All repos matching repo choice
