name: 'artifacts cleanup'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # every night at 1 am UTC
  workflow_run:
    workflows:
      - send discord message
    types: 
      - completed

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: c-hive/gha-remove-artifacts@v1
        with:
          age: 10 minutes # Set this to 0 to delete all artifacts
