name: "deploy"

on:
  workflow_dispatch:
jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: "Clone config Repository"
        uses: actions/checkout@master
        with:
          repository: FluffyTal-es/fluffy-configs
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: '.'
      
      - name: "Move configs to right path"
        run: |
          mkdir -p resources/[configs]
          mv config/* resources/[configs]/
          rm -r config

      - name: "Clone dev-tools Repository"
        uses: actions/checkout@master
        with:
          repository: FluffyTal-es/fluffy-dev-tools
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: 'resources/[dev]'

      - name: "Quick check"
        run: |
          ls -al
          ls -al resources/[dev]
          ls -al resources/[configs]/

      - uses: actions/upload-artifact@v2
        with:
          name: fluffytales
          path: '.'

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: fluffytales

      - name: "Deploy configs on server"
        env:
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          local_dir: "."
          remote_dir: "/root/fivem_resources"
        run: |
          mkdir ~/.ssh
          echo "$remote_key" > ~/.ssh/id_github
          chmod 600 ~/.ssh/id_github
          rsync -avzrI -e "ssh -p ${remote_port} -i ~/.ssh/id_github -o StrictHostKeyChecking=no" ${local_dir} ${remote_user}@${remote_host}:${remote_dir}
          rm ~/.ssh/id_github
