name: "deploy"

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Which repository to deploy'
        required: true
        default: 'all' 
        type: string
      live:
        description: 'Deploy to live server?'
        required: true
        default: 'yes' 
        type: choice
        options:
        - 'yes'
        - 'no'
      sha:
        description: 'Last commit SHA'
        required: false
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: "Prepare message"
      run: echo {\"repo\":\"${{github.event.inputs.repo}}\", \"live\":\"${{github.event.inputs.live}}\"}  > status.json

    - uses: actions/upload-artifact@v2
      with:
        name: status
        path: status.json

    - name: Fetch local action
      uses: actions/checkout@v3

    - name: Find repos to deploy
      uses: ./
      id: set-matrix
      with:
        token: ${{ secrets.DEPLOY_TOKEN }}
        repos: ${{ github.event.inputs.repo }}

    - name: debug
      run: echo ${{ steps.set-matrix.outputs.matrix }}

  clone:
    needs: [prepare]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    
    steps:
      - name: Clone resource repository
        uses: actions/checkout@master
        with:
          repository: FluffyTal-es/${{ matrix.name }}
          token: ${{ secrets.DEPLOY_TOKEN }}
          path:  ${{ matrix.path }}
      
      - name: Remove .git folder
        run: rm -rf ${{ matrix.path }}/.git

      - name: "Move configs to right path"
        if: matrix.name == 'fluffy-configs'
        env: 
          CONFIG: ${{ matrix.path }}
        run: |
          cp resources/\[configs\]/fluffy-configs/config/*.cfg resources/[\configs\]/
          mv resources/\[configs\]/fluffy-configs/server.cfg ./server.cfg
          rm -r resources/\[configs\]/fluffy-configs

      - name: Delete related qb resource 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: find /opt/fivem_resources/resources -maxdepth 3 -type d -name "${{ matrix.qb }}*" | grep -v 'fluffy' | xargs rm -rf
      
      - uses: FluffyTal-es/fluffy-auto-release@latest
        if: ${{ github.event.inputs.repo != 'all' }} 
        with:
          repo_token: "${{ secrets.DEPLOY_TOKEN }}"
          automatic_release_tag: "latest"
          repository: ${{ matrix.name }}
          sha: ${{ github.event.inputs.sha }}

      - uses: actions/upload-artifact@v2
        with:
          name: fluffytales
          path: '.'

  push:
    needs: [clone]
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: fluffytales

      - name: "Deploy resources to server"
        env:
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          local_dir: "."
          remote_dir: "/opt/fivem_resources"
        run: |
          mkdir ~/.ssh
          echo "$remote_key" > ~/.ssh/id_github
          chmod 600 ~/.ssh/id_github
          rsync -avzrIO --no-perms -e "ssh -p ${remote_port} -i ~/.ssh/id_github -o StrictHostKeyChecking=no" ${local_dir} ${remote_user}@${remote_host}:${remote_dir}
          rm ~/.ssh/id_github
