name: "deploy new version to server"

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Clone config Repository"
        uses: actions/checkout@master
        with:
          repository: FluffyTal-es/fluffy-configs
          token: ${{ secrets.DEPLOY_TOKEN }}

      - name: "Deploy configs on server"
        env:
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          local_dir: "."
          remote_dir: "/root/fivem_resources"
        run: |
          mkdir ~/.ssh
          mkdir -p resources/[configs]
          echo "$remote_key" > ~/.ssh/id_github
          chmod 600 ~/.ssh/id_github
          mv config/* resources/[configs]/
          rm config
          rsync -avzr --delete -e "ssh -p ${remote_port} -i ~/.ssh/id_github -o StrictHostKeyChecking=no" ${local_dir} ${remote_user}@${remote_host}:${remote_dir}
          rm ~/.ssh/id_github
