name: "discord"

on:
  workflow_run:
    workflows:
      - deploy
    types: 
      - completed
jobs:
  get-status:
    outputs:
      repo: ${{ steps.workflow-status.outputs.repo }}
      live: ${{ steps.workflow-status.outputs.live }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: get-artifact-id
        with:
          github-token: ${{ secrets.DEPLOY_TOKEN }}
          result-encoding: string
          script: |
            const result = await github.rest.actions.listWorkflowRunArtifacts({
              owner: '${{github.repository_owner}}',
              repo: '${{github.event.repository.name}}',
              run_id: ${{github.event.workflow_run.id}}
            })
            return result.data.artifacts.filter(a => a.name === 'status')[0].archive_download_url
      - name: Get workflow status
        id: workflow-status
        run: |
          echo "${{steps.get-artifact-id.outputs.result}}"
          curl -L -H "Authorization: token ${{github.token}}" \
            -H "Accept: application/vnd.github.v3+json" \
            -o status.zip \
            ${{steps.get-artifact-id.outputs.result}}
          unzip status.zip
          echo "REPO= $(jq '.repo' status.json)" >> $GITHUB_ENV
          echo "LIVE= $(jq '.live' status.json)" >> $GITHUB_ENV
          echo "::set-output name=repo::$REPO"
          echo "::set-output name=live::$LIVE"
          echo "$REPO"
          echo "$LIVE"
  on-success:
    needs: [get-status]
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo ${{ needs.get-status.outputs.repo }}
      - run: echo ${{ needs.get-status.outputs.live }}
      - name: "Hurray!"
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          avatar_url: "https://cdn.fluffytal.es/servericon.png"
          color: "#00ff72"
          username: "FluffyTales GitBot"
          message: ":+1: Hurray! An updated dropped on the Server!\n\nHit the link and find the details!\n\n:link: ${{ github.event.workflow_run.html_url}}\n\nSee you next time! :kissing_heart:"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: "Nay!"
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          avatar_url: "https://cdn.fluffytal.es/servericon.png"
          color: "#ff006a"
          username: "FluffyTales GitBot"
          message: ":-1: Nay Nay Nay! That ship has sunk somewhere in between!\n\nHit the link and find the details!\n\n:link: ${{ github.event.workflow_run.html_url}}\n\nSee you next time! :kissing_heart:"
