name: "discord"

on:
  workflow_run:
    workflows:
      - deploy
    types: 
      - completed
jobs:
  get-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: get-artifact-id
        with:
          github-token: ${{ secrets.DEPLOY_TOKEN }}
          result-encoding: string
          script: |
            const result = await github.rest.actions.listWorkflowRunArtifacts({
              owner: '${{github.repository_owner}}',
              repo: '${{github.event.repository.name}}',
              run_id: ${{github.event.workflow_run.id}}
            })
            return result.data.artifacts.filter(a => a.name === 'status')[0].id
      - name: Get workflow status
        run: |
          echo "${{steps.get-artifact-id.outputs.result}}"
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: "Hurray!"
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          avatar_url: "https://cdn.fluffytal.es/servericon.png"
          color: "#00ff72"
          username: "FluffyTales GitBot"
          message: ":+1: Hurray! An updated dropped on the Server!\n\nHit the link and find the details!\n\n:link: ${{ github.event.workflow_run.html_url}}\n\nSee you next time! :kissing_heart:"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: "Nay!"
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          avatar_url: "https://cdn.fluffytal.es/servericon.png"
          color: "#ff006a"
          username: "FluffyTales GitBot"
          message: ":-1: Nay Nay Nay! That ship has sunk somewhere in between!\n\nHit the link and find the details!\n\n:link: ${{ github.event.workflow_run.html_url}}\n\nSee you next time! :kissing_heart:"
