name: "discord"

on:
  workflow_run:
    workflows:
      - deploy
    types: 
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: "Hurray!"
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          avatar_url: "https://cdn.fluffytal.es/servericon.png"
          color: "#00ff72"
          username: "FluffyTales GitBot"
          message: "Hurray! An updated dropped on the Server! \n Hit the link, find the details! \n ${{ github.event.workflow_run.html_url}}"

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: "Nay!"
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          avatar_url: "https://cdn.fluffytal.es/servericon.png"
          color: "#ff006a"
          username: "FluffyTales GitBot"
          message: "Nay Nay Nay! That ship has sunk somewhere in between! \n Hit the link, find the details! \n ${{ github.event.workflow_run.html_url}}"
